#!/usr/bin/env python3
"""Generate and verify documentation for public Agent and Browser defaults."""

import argparse
import inspect
import tomllib
from pathlib import Path
from typing import Any

from pydantic_core import PydanticUndefined

from browser_use import Agent, BrowserProfile
from browser_use.browser.extensions import DEFAULT_EXTENSION_SPECS

PROJECT_ROOT = Path(__file__).resolve().parents[1]
OUTPUT_PATH = PROJECT_ROOT / 'docs' / 'configuration-defaults.md'

AGENT_PARAMETERS = (
	'use_vision',
	'max_failures',
	'max_actions_per_step',
	'use_thinking',
	'flash_mode',
	'llm_timeout',
	'step_timeout',
	'final_response_after_failure',
	'message_compaction',
	'enable_planning',
	'directly_open_url',
	'context',
)

BROWSER_PARAMETERS = (
	'headless',
	'keep_alive',
	'allowed_domains',
	'prohibited_domains',
	'enable_default_extensions',
	'cross_origin_iframes',
	'minimum_wait_page_load_time',
	'wait_for_network_idle_page_load_time',
	'wait_between_actions',
	'highlight_elements',
	'paint_order_filtering',
	'accept_downloads',
	'auto_download_pdfs',
	'block_ip_addresses',
)


def _format_default(value: Any) -> str:
	"""Format a Python default as a stable Markdown code span."""
	if value is PydanticUndefined:
		return '`environment-dependent`'
	return f'`{value!r}`'


def generate_document() -> str:
	"""Build the configuration-default reference from runtime definitions."""
	agent_signature = inspect.signature(Agent.__init__)
	run_signature = inspect.signature(Agent.run)
	with (PROJECT_ROOT / 'pyproject.toml').open('rb') as project_file:
		requires_python = tomllib.load(project_file)['project']['requires-python']

	lines = [
		'# Configuration defaults',
		'',
		'> Generated by `scripts/generate_configuration_defaults.py`; do not edit manually.',
		'',
		'These values come directly from the public Python API and are checked by pre-commit.',
		'',
		'## Runtime',
		'',
		f'- Supported Python: `{requires_python}`',
		'- Repository development interpreter: `.python-version`',
		'',
		'## Agent',
		'',
		'| Parameter | Default |',
		'| --- | --- |',
	]
	for parameter_name in AGENT_PARAMETERS:
		default = agent_signature.parameters[parameter_name].default
		lines.append(f'| `Agent(..., {parameter_name}=...)` | {_format_default(default)} |')
	lines.append(f'| `Agent.run(max_steps=...)` | {_format_default(run_signature.parameters["max_steps"].default)} |')

	lines.extend(
		[
			'',
			'`llm_timeout=None` means the timeout is selected from the model family. '
			'When no LLM is supplied or configured, `ChatBrowserUse()` is used.',
			'',
			'## Browser',
			'',
			'| Parameter | Default |',
			'| --- | --- |',
		]
	)
	for parameter_name in BROWSER_PARAMETERS:
		field = BrowserProfile.model_fields[parameter_name]
		default = field.default
		lines.append(f'| `Browser(..., {parameter_name}=...)` | {_format_default(default)} |')

	lines.extend(
		[
			'',
			'`enable_default_extensions` defaults to `True`; `BROWSER_USE_DISABLE_EXTENSIONS` can override it at runtime.',
			'Browser installation and default-extension preparation finish before timed browser launch events begin.',
			'',
			'### Pinned default extensions',
			'',
			'| Extension | ID | Version | SHA-256 |',
			'| --- | --- | --- | --- |',
			'',
		]
	)
	for extension in DEFAULT_EXTENSION_SPECS:
		lines.insert(
			-1,
			f'| {extension.name} | `{extension.extension_id}` | `{extension.version}` | `{extension.sha256}` |',
		)
	return '\n'.join(lines)


def main() -> int:
	"""Write the generated file or fail when the committed copy has drifted."""
	parser = argparse.ArgumentParser(description=__doc__)
	parser.add_argument('--write', action='store_true', help='Update the generated documentation in place.')
	args = parser.parse_args()
	expected = generate_document()

	if args.write:
		OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
		OUTPUT_PATH.write_text(expected, encoding='utf-8')
		return 0

	actual = OUTPUT_PATH.read_text(encoding='utf-8') if OUTPUT_PATH.exists() else ''
	if actual != expected:
		print(f'{OUTPUT_PATH.relative_to(PROJECT_ROOT)} is stale; run this script with --write.')
		return 1
	return 0


if __name__ == '__main__':
	raise SystemExit(main())
